# Generated by Django 3.0.3 on 2020-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster_img', models.ImageField(upload_to='images')),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
