# Generated by Django 3.0.3 on 2020-03-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0003_auto_20200317_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='desc',
        ),
    ]
