# Generated by Django 3.0.3 on 2020-03-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0004_remove_movie_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Title',
        ),
    ]
