# Generated by Django 3.0.3 on 2020-03-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0005_auto_20200318_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='lang',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(),
        ),
    ]
