# Generated by Django 3.0.3 on 2020-03-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0007_auto_20200318_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField()),
                ('job_id', models.TextField()),
                ('start_time', models.TextField()),
                ('results_output_path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='job_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='job_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='tweets',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
