# Generated by Django 3.0.3 on 2020-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0008_auto_20200330_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='sentiments_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
