# Generated by Django 3.0.3 on 2020-03-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0009_auto_20200331_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='job_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='negative',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='neutral',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='positive',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='total',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
