# Generated by Django 3.0.3 on 2020-04-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0010_auto_20200331_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sentiments_count',
        ),
    ]
