# Generated by Django 3.0.3 on 2020-04-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0011_remove_job_sentiments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
