# Generated by Django 3.0.3 on 2020-04-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0012_title_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sentiments_count',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
