# Generated by Django 3.0.3 on 2020-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0013_job_sentiments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='latest_job_date',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
