# Generated by Django 3.0.3 on 2020-04-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_title', '0014_title_latest_job_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('job_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='title',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='tweets',
        ),
    ]
